In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [3]:
my_data = pd.read_csv("C://Users//QWERTY//Desktop//PROJECT//training_data_for_students_0.csv")
# So first of all let's get introduced with out dataset
my_data

C:\Users\QWERTY\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (16,18,22,23,25,30,31,36,37,95,100,101,106,107) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,search_query,search_id,search_type,search_datetime,search_source,search_user_location,provider,flight_date,routes,origin_country,...,leg_3_segment_0_baggage_unit,leg_3_segment_1_baggage_unit,leg_3_segment_2_baggage_unit,leg_3_segment_3_baggage_unit,leg_3_segment_4_baggage_unit,leg_4_segment_0_baggage_unit,leg_4_segment_1_baggage_unit,leg_4_segment_2_baggage_unit,leg_4_segment_3_baggage_unit,leg_4_segment_4_baggage_unit
0,KZO-ALA201910081000E,5ce7d3d9-1ff7-4606-bd41-abedf1c457f0,OW,2019-09-08 16:41:56,\N,\N,AD,2019-10-08,KZO-ALA,KZ,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,KZO-ALA201910081000E,5ce7d3d9-1ff7-4606-bd41-abedf1c457f0,OW,2019-09-08 16:41:56,\N,\N,SS,2019-10-08,KZO-ALA,KZ,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,KZO-ALA201910081000E,5ce7d3d9-1ff7-4606-bd41-abedf1c457f0,OW,2019-09-08 16:41:56,\N,\N,SS,2019-10-08,KZO-ALA,KZ,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,KZO-ALA201910081000E,5ce7d3d9-1ff7-4606-bd41-abedf1c457f0,OW,2019-09-08 16:41:56,\N,\N,AD,2019-10-08,KZO-ALA,KZ,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,KZO-ALA201910081000E,5ce7d3d9-1ff7-4606-bd41-abedf1c457f0,OW,2019-09-08 16:41:56,\N,\N,AD,2019-10-08,KZO-ALA,KZ,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,ALA-IST20191003IST-ALA201910062000E,1f93c037-0d3e-4a50-9fdd-bced5d687b1d,RT,2019-09-12 09:49:43,\N,\N,SS,2019-10-03,ALA-IST,KZ,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
249996,ALA-IST20191003IST-ALA201910062000E,1f93c037-0d3e-4a50-9fdd-bced5d687b1d,RT,2019-09-12 09:49:43,\N,\N,SS,2019-10-03,ALA-IST,KZ,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
249997,ALA-IST20191003IST-ALA201910062000E,1f93c037-0d3e-4a50-9fdd-bced5d687b1d,RT,2019-09-12 09:49:43,\N,\N,SS,2019-10-03,ALA-IST,KZ,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
249998,ALA-IST20191003IST-ALA201910062000E,1f93c037-0d3e-4a50-9fdd-bced5d687b1d,RT,2019-09-12 09:49:43,\N,\N,AD,2019-10-03,ALA-IST,KZ,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
249999,ALA-IST20191003IST-ALA201910062000E,1f93c037-0d3e-4a50-9fdd-bced5d687b1d,RT,2019-09-12 09:49:43,\N,\N,AD,2019-10-03,ALA-IST,KZ,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [4]:
my_data.duplicated(subset=None, keep='first')

0         False
1         False
2         False
3         False
4         False
          ...
249995    False
249996    False
249997    False
249998    False
249999    False
Length: 250000, dtype: bool

In [5]:
my_data1 = my_data.drop_duplicates(subset=None, keep='first', inplace=False)

In [6]:
my_data2 = my_data1[my_data1.is_refundable != '\\N']

In [7]:
my_data3 = my_data2[my_data2.leg_0_segment_0_baggage_value != '\\N']

In [8]:
my_data4 = my_data3[my_data3.leg_0_segment_1_flight_number != '\\N']

In [9]:
my_data5 = my_data4[my_data4.leg_0_segment_1_departure_datetime != '\\N']

In [10]:
my_data6 = my_data5[my_data5.leg_0_segment_1_from_airport_code != '\\N']

In [11]:
my_clean_data = my_data6

In [12]:
my_data3 = pd.get_dummies(my_clean_data, columns=['routes'])

In [13]:
my_data4 = pd.get_dummies(my_data3, columns=['cabin_class'])

In [14]:
import pandas as pd
import tensorflow as tf
my_data5 = my_data4.drop(['search_query','leg_0_segment_4_from_airport_code','leg_0_segment_2_from_airport_code','leg_0_segment_3_from_airport_code','leg_0_segment_1_flight_number','leg_0_segment_0_departure_datetime','leg_0_segment_2_departure_datetime','leg_0_segment_1_departure_datetime','search_id','search_type','search_datetime', 'search_source','search_user_location','provider','flight_date', 'origin_country','destination_country','original_amount','original_currency','original_currency_rate','currency','price_USD','offers_count','leg_0_segment_0_airline','leg_0_segment_0_flight_number','leg_0_segment_0_from_airport_code','leg_0_segment_0_from_city_code','leg_0_segment_0_from_country_code','leg_0_segment_0_from_latitude','leg_0_segment_0_from_longitude','leg_0_segment_0_arrival_datetime','leg_0_segment_0_to_airport_code','leg_0_segment_0_to_city_code','leg_0_segment_0_to_country_code','leg_0_segment_0_to_latitude','leg_0_segment_0_to_longitude','leg_0_segment_1_airline','leg_0_segment_1_from_city_code','leg_0_segment_1_from_country_code','leg_0_segment_1_from_latitude','leg_0_segment_1_from_longitude','leg_0_segment_1_arrival_datetime','leg_0_segment_1_to_airport_code','leg_0_segment_1_to_city_code','leg_0_segment_1_to_country_code','leg_0_segment_1_to_latitude','leg_0_segment_1_to_longitude','leg_0_segment_2_airline','leg_0_segment_2_flight_number','leg_0_segment_2_from_city_code','leg_0_segment_2_from_country_code','leg_0_segment_2_from_latitude','leg_0_segment_2_from_longitude','leg_0_segment_2_arrival_datetime','leg_0_segment_2_to_airport_code','leg_0_segment_2_to_city_code','leg_0_segment_2_to_country_code','leg_0_segment_2_to_latitude','leg_0_segment_2_to_longitude','leg_0_segment_3_airline','leg_0_segment_3_flight_number','leg_0_segment_3_departure_datetime','leg_0_segment_3_from_city_code','leg_0_segment_3_from_country_code','leg_0_segment_3_from_latitude','leg_0_segment_3_from_longitude','leg_0_segment_3_arrival_datetime','leg_0_segment_3_to_airport_code','leg_0_segment_3_to_city_code','leg_0_segment_3_to_country_code','leg_0_segment_3_to_latitude','leg_0_segment_3_to_longitude','leg_0_segment_4_airline','leg_0_segment_4_flight_number','leg_0_segment_4_departure_datetime','leg_0_segment_4_from_city_code','leg_0_segment_4_from_country_code','leg_0_segment_4_from_latitude','leg_0_segment_4_from_longitude','leg_0_segment_4_arrival_datetime','leg_0_segment_4_to_airport_code','leg_0_segment_4_to_city_code','leg_0_segment_4_to_country_code','leg_0_segment_4_to_latitude','leg_0_segment_4_to_longitude','leg_1_segment_0_airline','leg_1_segment_0_flight_number','leg_1_segment_0_departure_datetime','leg_1_segment_0_from_airport_code','leg_1_segment_0_from_city_code','leg_1_segment_0_from_country_code','leg_1_segment_0_from_latitude','leg_1_segment_0_from_longitude','leg_1_segment_0_arrival_datetime','leg_1_segment_0_to_airport_code','leg_1_segment_0_to_city_code','leg_1_segment_0_to_country_code','leg_1_segment_0_to_latitude','leg_1_segment_0_to_longitude','leg_1_segment_1_airline','leg_1_segment_1_flight_number','leg_1_segment_1_departure_datetime','leg_1_segment_1_from_airport_code','leg_1_segment_1_from_city_code','leg_1_segment_1_from_country_code','leg_1_segment_1_from_latitude','leg_1_segment_1_from_longitude','leg_1_segment_1_arrival_datetime','leg_1_segment_1_to_airport_code','leg_1_segment_1_to_city_code','leg_1_segment_1_to_country_code','leg_1_segment_1_to_latitude','leg_1_segment_1_to_longitude','leg_1_segment_2_airline','leg_1_segment_2_flight_number','leg_1_segment_2_departure_datetime','leg_1_segment_2_from_airport_code','leg_1_segment_2_from_city_code','leg_1_segment_2_from_country_code','leg_1_segment_2_from_latitude','leg_1_segment_2_from_longitude','leg_1_segment_2_arrival_datetime','leg_1_segment_2_to_airport_code','leg_1_segment_2_to_city_code','leg_1_segment_2_to_country_code','leg_1_segment_2_to_latitude','leg_1_segment_2_to_longitude','leg_1_segment_3_airline','leg_1_segment_3_flight_number','leg_1_segment_3_departure_datetime','leg_1_segment_3_from_airport_code','leg_1_segment_3_from_city_code','leg_1_segment_3_from_country_code','leg_1_segment_3_from_latitude','leg_1_segment_3_from_longitude','leg_1_segment_3_arrival_datetime','leg_1_segment_3_to_airport_code','leg_1_segment_3_to_city_code','leg_1_segment_3_to_country_code','leg_1_segment_3_to_latitude','leg_1_segment_3_to_longitude','leg_1_segment_4_airline','leg_1_segment_4_flight_number','leg_1_segment_4_departure_datetime','leg_1_segment_4_from_airport_code','leg_1_segment_4_from_city_code','leg_1_segment_4_from_country_code','leg_1_segment_4_from_latitude','leg_1_segment_4_from_longitude','leg_1_segment_4_arrival_datetime','leg_1_segment_4_to_airport_code','leg_1_segment_4_to_city_code','leg_1_segment_4_to_country_code','leg_1_segment_4_to_latitude','leg_1_segment_4_to_longitude','leg_2_segment_0_airline','leg_2_segment_0_flight_number','leg_2_segment_0_departure_datetime','leg_2_segment_0_from_airport_code','leg_2_segment_0_from_city_code','leg_2_segment_0_from_country_code','leg_2_segment_0_from_latitude','leg_2_segment_0_from_longitude','leg_2_segment_0_arrival_datetime','leg_2_segment_0_to_airport_code','leg_2_segment_0_to_city_code','leg_2_segment_0_to_country_code','leg_2_segment_0_to_latitude','leg_2_segment_0_to_longitude','leg_2_segment_1_airline','leg_2_segment_1_flight_number','leg_2_segment_1_departure_datetime','leg_2_segment_1_from_airport_code','leg_2_segment_1_from_city_code','leg_2_segment_1_from_country_code','leg_2_segment_1_from_latitude','leg_2_segment_1_from_longitude','leg_2_segment_1_arrival_datetime','leg_2_segment_1_to_airport_code','leg_2_segment_1_to_city_code','leg_2_segment_1_to_country_code','leg_2_segment_1_to_latitude','leg_2_segment_1_to_longitude','leg_2_segment_2_airline','leg_2_segment_2_flight_number','leg_2_segment_2_departure_datetime','leg_2_segment_2_from_airport_code','leg_2_segment_2_from_city_code','leg_2_segment_2_from_country_code','leg_2_segment_2_from_latitude','leg_2_segment_2_from_longitude','leg_2_segment_2_arrival_datetime','leg_2_segment_2_to_airport_code','leg_2_segment_2_to_city_code','leg_2_segment_2_to_country_code','leg_2_segment_2_to_latitude','leg_2_segment_2_to_longitude','leg_2_segment_3_airline','leg_2_segment_3_flight_number','leg_2_segment_3_departure_datetime','leg_2_segment_3_from_airport_code','leg_2_segment_3_from_city_code','leg_2_segment_3_from_country_code','leg_2_segment_3_from_latitude','leg_2_segment_3_from_longitude','leg_2_segment_3_arrival_datetime','leg_2_segment_3_to_airport_code','leg_2_segment_3_to_city_code','leg_2_segment_3_to_country_code','leg_2_segment_3_to_latitude','leg_2_segment_3_to_longitude','leg_2_segment_4_airline','leg_2_segment_4_flight_number','leg_2_segment_4_departure_datetime','leg_2_segment_4_from_airport_code','leg_2_segment_4_from_city_code','leg_2_segment_4_from_country_code','leg_2_segment_4_from_latitude','leg_2_segment_4_from_longitude','leg_2_segment_4_arrival_datetime','leg_2_segment_4_to_airport_code','leg_2_segment_4_to_city_code','leg_2_segment_4_to_country_code','leg_2_segment_4_to_latitude','leg_2_segment_4_to_longitude','leg_3_segment_0_airline','leg_3_segment_0_flight_number','leg_3_segment_0_departure_datetime','leg_3_segment_0_from_airport_code','leg_3_segment_0_from_city_code','leg_3_segment_0_from_country_code','leg_3_segment_0_from_latitude','leg_3_segment_0_from_longitude','leg_3_segment_0_arrival_datetime','leg_3_segment_0_to_airport_code','leg_3_segment_0_to_city_code','leg_3_segment_0_to_country_code','leg_3_segment_0_to_latitude','leg_3_segment_0_to_longitude','leg_3_segment_1_airline','leg_3_segment_1_flight_number','leg_3_segment_1_departure_datetime','leg_3_segment_1_from_airport_code','leg_3_segment_1_from_city_code','leg_3_segment_1_from_country_code','leg_3_segment_1_from_latitude','leg_3_segment_1_from_longitude','leg_3_segment_1_arrival_datetime','leg_3_segment_1_to_airport_code','leg_3_segment_1_to_city_code','leg_3_segment_1_to_country_code','leg_3_segment_1_to_latitude','leg_3_segment_1_to_longitude','leg_3_segment_2_airline','leg_3_segment_2_flight_number','leg_3_segment_2_departure_datetime','leg_3_segment_2_from_airport_code','leg_3_segment_2_from_city_code','leg_3_segment_2_from_country_code','leg_3_segment_2_from_latitude','leg_3_segment_2_from_longitude','leg_3_segment_2_arrival_datetime','leg_3_segment_2_to_airport_code','leg_3_segment_2_to_city_code','leg_3_segment_2_to_country_code','leg_3_segment_2_to_latitude','leg_3_segment_2_to_longitude','leg_3_segment_3_airline','leg_3_segment_3_flight_number','leg_3_segment_3_departure_datetime','leg_3_segment_3_from_airport_code','leg_3_segment_3_from_city_code','leg_3_segment_3_from_country_code','leg_3_segment_3_from_latitude','leg_3_segment_3_from_longitude','leg_3_segment_3_arrival_datetime','leg_3_segment_3_to_airport_code','leg_3_segment_3_to_city_code','leg_3_segment_3_to_country_code','leg_3_segment_3_to_latitude','leg_3_segment_3_to_longitude','leg_3_segment_4_airline','leg_3_segment_4_flight_number','leg_3_segment_4_departure_datetime','leg_3_segment_4_from_airport_code','leg_3_segment_4_from_city_code','leg_3_segment_4_from_country_code','leg_3_segment_4_from_latitude','leg_3_segment_4_from_longitude','leg_3_segment_4_arrival_datetime','leg_3_segment_4_to_airport_code','leg_3_segment_4_to_city_code','leg_3_segment_4_to_country_code','leg_3_segment_4_to_latitude','leg_3_segment_4_to_longitude','leg_4_segment_0_airline','leg_4_segment_0_flight_number','leg_4_segment_0_departure_datetime','leg_4_segment_0_from_airport_code','leg_4_segment_0_from_city_code','leg_4_segment_0_from_country_code','leg_4_segment_0_from_latitude','leg_4_segment_0_from_longitude','leg_4_segment_0_arrival_datetime','leg_4_segment_0_to_airport_code','leg_4_segment_0_to_city_code','leg_4_segment_0_to_country_code','leg_4_segment_0_to_latitude','leg_4_segment_0_to_longitude','leg_4_segment_1_airline','leg_4_segment_1_flight_number','leg_4_segment_1_departure_datetime','leg_4_segment_1_from_airport_code','leg_4_segment_1_from_city_code','leg_4_segment_1_from_country_code','leg_4_segment_1_from_latitude','leg_4_segment_1_from_longitude','leg_4_segment_1_arrival_datetime','leg_4_segment_1_to_airport_code','leg_4_segment_1_to_city_code','leg_4_segment_1_to_country_code','leg_4_segment_1_to_latitude','leg_4_segment_1_to_longitude','leg_4_segment_2_airline','leg_4_segment_2_flight_number','leg_4_segment_2_departure_datetime','leg_4_segment_2_from_airport_code','leg_4_segment_2_from_city_code','leg_4_segment_2_from_country_code','leg_4_segment_2_from_latitude','leg_4_segment_2_from_longitude','leg_4_segment_2_arrival_datetime','leg_4_segment_2_to_airport_code','leg_4_segment_2_to_city_code','leg_4_segment_2_to_country_code','leg_4_segment_2_to_latitude','leg_4_segment_2_to_longitude','leg_4_segment_3_airline','leg_4_segment_3_flight_number','leg_4_segment_3_departure_datetime','leg_4_segment_3_from_airport_code','leg_4_segment_3_from_city_code','leg_4_segment_3_from_country_code','leg_4_segment_3_from_latitude','leg_4_segment_3_from_longitude','leg_4_segment_3_arrival_datetime','leg_4_segment_3_to_airport_code','leg_4_segment_3_to_city_code','leg_4_segment_3_to_country_code','leg_4_segment_3_to_latitude','leg_4_segment_3_to_longitude','leg_4_segment_4_airline','leg_4_segment_4_flight_number','leg_4_segment_4_departure_datetime','leg_4_segment_4_from_airport_code','leg_4_segment_4_from_city_code','leg_4_segment_4_from_country_code','leg_4_segment_4_from_latitude','leg_4_segment_4_from_longitude','leg_4_segment_4_arrival_datetime','leg_4_segment_4_to_airport_code','leg_4_segment_4_to_city_code','leg_4_segment_4_to_country_code','leg_4_segment_4_to_latitude','leg_4_segment_4_to_longitude','leg_0_segment_1_baggage_value','leg_0_segment_2_baggage_value','leg_0_segment_3_baggage_value','leg_0_segment_4_baggage_value','leg_1_segment_0_baggage_value','leg_1_segment_1_baggage_value','leg_1_segment_2_baggage_value','leg_1_segment_3_baggage_value','leg_1_segment_4_baggage_value','leg_2_segment_0_baggage_value','leg_2_segment_1_baggage_value','leg_2_segment_2_baggage_value','leg_2_segment_3_baggage_value','leg_2_segment_4_baggage_value','leg_3_segment_0_baggage_value','leg_3_segment_1_baggage_value','leg_3_segment_2_baggage_value','leg_3_segment_3_baggage_value','leg_3_segment_4_baggage_value','leg_4_segment_0_baggage_value','leg_4_segment_1_baggage_value','leg_4_segment_2_baggage_value','leg_4_segment_3_baggage_value','leg_4_segment_4_baggage_value','leg_0_segment_0_baggage_unit','leg_0_segment_1_baggage_unit','leg_0_segment_2_baggage_unit','leg_0_segment_3_baggage_unit','leg_0_segment_4_baggage_unit','leg_1_segment_0_baggage_unit','leg_1_segment_1_baggage_unit','leg_1_segment_2_baggage_unit','leg_1_segment_3_baggage_unit','leg_1_segment_4_baggage_unit','leg_2_segment_0_baggage_unit','leg_2_segment_1_baggage_unit','leg_2_segment_2_baggage_unit','leg_2_segment_3_baggage_unit','leg_2_segment_4_baggage_unit','leg_3_segment_0_baggage_unit','leg_3_segment_1_baggage_unit','leg_3_segment_2_baggage_unit','leg_3_segment_3_baggage_unit','leg_3_segment_4_baggage_unit','leg_4_segment_0_baggage_unit','leg_4_segment_1_baggage_unit','leg_4_segment_2_baggage_unit','leg_4_segment_3_baggage_unit','leg_4_segment_4_baggage_unit'],axis=1)
my_data5

,pass_adt,pass_child,pass_inf,pass_stud,is_owc,is_direct,leg_0_segment_1_from_airport_code,is_refundable,is_booked,leg_0_segment_0_baggage_value,...,routes_ZIA-TAS,routes_ZIA-TSE,routes_ZIA-UKK,routes_ZIA-URA,routes_ZIA-VNO,routes_ZIA-VOZ,routes_ZIA-WAW,routes_ZMU-ALA,cabin_class_BUSINESS,cabin_class_ECONOMY
3,1,0,0,0,0,0,TSE,1,0,1,...,0,0,0,0,0,0,0,0,0,1
4,1,0,0,0,0,0,TSE,1,0,1,...,0,0,0,0,0,0,0,0,0,1
5,1,0,0,0,0,0,TSE,1,0,1,...,0,0,0,0,0,0,0,0,0,1
6,1,0,0,0,0,0,TSE,1,0,1,...,0,0,0,0,0,0,0,0,0,1
7,1,0,0,0,0,0,TSE,1,0,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249979,2,0,0,0,1,0,SCO,0,0,30,...,0,0,0,0,0,0,0,0,0,1
249982,2,0,0,0,1,0,TSE,1,0,1,...,0,0,0,0,0,0,0,0,0,1
249994,2,0,0,0,0,0,SCO,0,0,30,...,0,0,0,0,0,0,0,0,0,1
249998,2,0,0,0,0,0,KBP,0,0,0,...,0,0,0,0,0,0,0,0,0,1
249999,2,0,0,0,0,0,KBP,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [15]:
my_data6 = pd.get_dummies(my_data5, columns=['leg_0_segment_1_from_airport_code'])
my_data6

,pass_adt,pass_child,pass_inf,pass_stud,is_owc,is_direct,is_refundable,is_booked,leg_0_segment_0_baggage_value,routes_AAQ-DME,...,leg_0_segment_1_from_airport_code_XNN,leg_0_segment_1_from_airport_code_YKS,leg_0_segment_1_from_airport_code_YUL,leg_0_segment_1_from_airport_code_YVR,leg_0_segment_1_from_airport_code_YYZ,leg_0_segment_1_from_airport_code_ZAG,leg_0_segment_1_from_airport_code_ZIA,leg_0_segment_1_from_airport_code_ZRB,leg_0_segment_1_from_airport_code_ZRH,leg_0_segment_1_from_airport_code_ZYR
3,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249979,2,0,0,0,1,0,0,0,30,0,...,0,0,0,0,0,0,0,0,0,0
249982,2,0,0,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
249994,2,0,0,0,0,0,0,0,30,0,...,0,0,0,0,0,0,0,0,0,0
249998,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249999,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
NotBooked = my_data6[my_data6['is_booked']==0]
IsBooked = my_data6[my_data6['is_booked']==1]

In [17]:
NotBooked = NotBooked.sample(IsBooked.shape[0] * 2)

In [18]:
NotBooked.shape, IsBooked.shape

((5430, 1145), (2715, 1145))

In [19]:
my_balanced_data = IsBooked.append(NotBooked, ignore_index = True)
my_balanced_data

,pass_adt,pass_child,pass_inf,pass_stud,is_owc,is_direct,is_refundable,is_booked,leg_0_segment_0_baggage_value,routes_AAQ-DME,...,leg_0_segment_1_from_airport_code_XNN,leg_0_segment_1_from_airport_code_YKS,leg_0_segment_1_from_airport_code_YUL,leg_0_segment_1_from_airport_code_YVR,leg_0_segment_1_from_airport_code_YYZ,leg_0_segment_1_from_airport_code_ZAG,leg_0_segment_1_from_airport_code_ZIA,leg_0_segment_1_from_airport_code_ZRB,leg_0_segment_1_from_airport_code_ZRH,leg_0_segment_1_from_airport_code_ZYR
0,1,0,0,0,0,0,0,1,20,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,1,20,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,1,0,0,1,20,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8140,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
8141,1,1,1,0,0,0,1,0,20,0,...,0,0,0,0,0,0,0,0,0,0
8142,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
8143,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
8144,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
X = my_balanced_data.iloc[:, my_balanced_data.columns != 'is_booked']
y = my_balanced_data.iloc[:, my_balanced_data.columns == 'is_booked']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=0)

In [21]:
clf = DecisionTreeClassifier()

In [22]:
clf = clf.fit(X_train,y_train)

In [27]:
y_pred = clf.predict(X_test)

In [28]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7962356792144026

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[1425,  208],
       [ 290,  521]], dtype=int64)

In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.87      0.85      1633
           1       0.71      0.64      0.68       811

    accuracy                           0.80      2444
   macro avg       0.77      0.76      0.76      2444
weighted avg       0.79      0.80      0.79      2444